version: '3'

services:
  app:
    build: .
    command: bundle exec rails s -b '0.0.0.0'
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
    tty: true
    stdin_open: true
    links:
      - webpack

  webpack:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - 3035:3035
    volumes:
      - .:/usr/src/app

  #postgres:
    #image: postgres:11.1-alpine
    #volumes:
      #- ./pg-data:/var/lib/postgresql/data
    #env_file:
      #- .env.development
